spring:
  application:
    name: java-test-case-generate-agent
  main:
    banner-mode: off
  shell:
    interactive:
      enabled: true
#    theme:
#      name: agent
    command:
      script:
        enabled: true
#  ai:
#    vertex:
#      ai:
#        gemini:
#          project-id: tidy-vent-394615
#          chat:
#            options:
#              model: gemini-2.5-pro
#              temperature: 0.7
#          location: us-central1
#          credentials-uri: file:C:\Users\rhanu\AppData\Roaming\gcloud\application_default_credentials.json
  ai:
    vectorstore:
      pinecone:
        api-key: pcsk_4x6gPG_3uMiBWpeT2CXy1sHRnh5TLxTuC355EkrH2T6jNpWiiQh1FjURdy2vBSfMPTyArA
        index-name: spring-ai-index
        namespace: testagent
        content-field-name: document_content
    openai:
      chat:
        options:
          model: qwen/qwen3.5-397b-a17b # minimaxai/minimax-m2.5
#          reasoning-effort: low only for o1 models
          internal-tool-execution-enabled: true
          parallel-tool-calls: false
          verbosity: medium
          temperature: 0.1
      api-key: ${NVIDIA_API_KEY}
      base-url: https://integrate.api.nvidia.com
      embedding:
        options:
          model: baai/bge-m3
    retry:
      max-attempts: 3
      backoff:
        max-interval: 10s
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  ai:
#    google:
#      genai:
#        api-key: ${GOOGLE_API_KEY}
#        chat:
#          options:
#            model: gemini-2.5-flash
#            temperature: 1.0
#            thinking-level: high
#            google-search-retrieval: true
#            internal-tool-execution-enabled: true
#        location: global
#        project-id: tidy-vent-394615
#  ai:
#    openai:
#      base-url: https://generativelanguage.googleapis.com
#      chat:
#        options:
#          model: gemini-3.1-pro-preview
#        completions-path: /v1beta/openai/chat/completions
#      api-key: ${GOOGLE_API_KEY}

#logging:
#  level:
#    root: info
server:
  port: 8081
organization:
  ingest-data: true
